# Copied from https://github.com/MutinyWallet/mutiny-web/blob/master/.github/workflows/android-staging.yml
name: Release Android Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Checkout @satellite-earth/core
        uses: actions/checkout@v4
        with:
          repository: satellite-earth/core
          path: core
          ref: dev

      - name: Install @satellite-earth/core dependencies
        working-directory: core
        run: pnpm install

      - name: Build @satellite-earth/core
        working-directory: core
        run: pnpm build

      - name: Link core
        run: pnpm link ./core

      - name: Install app dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build

      - name: Capacitor sync
        run: npx cap sync

      - name: Build AAB
        working-directory: android
        run: ./gradlew clean bundleRelease --stacktrace

      # Temp Removed Sign AAB (F-Droid)

      - name: Build APK
        working-directory: android
        run: ./gradlew assembleRelease --stacktrace

      # Temp Removed Sign APK (F-Droid)

      # APK
      - name: Upload APK Asset
        id: upload-release-asset-fdroid-universal-apk
        uses: actions/upload-artifact@v3
        with:
          # modified to remove the -signed.apk
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          name: satellite-earth-fdroid-universal-dev.apk

      # AAB
      - name: Upload AAB Asset
        uses: actions/upload-artifact@v3
        with:
          path: android/app/build/outputs/bundle/release/app-release.aab
          name: satellite-earth-fdroid-dev.aab
